name=TMC22xxDriver
version=1.0.1
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=TCM2209/TMC22xx Stepper Motor Controller Library
paragraph=For TMC2202/2208/2209 and TMC2224/2225/2226, all architectures.
category=Device Control
url=https://github.com/mumanchu/TMC22xxDriver
architectures=*
